COMMON:
  DATA_PATH: data
TRAIN:
  TRAIN_DATA_PATH: train
  BATCH_SIZE: 1
  PRETRAIN: pretrain
  CKPT: checkpoints
  RESTORE: False
  MAX_ITER: 500
  LEARNING_RATE: 0.00001
  SOLVER: Adam
  MOMENTUM: 0.9
  NEGATIVE_OVERLAP: 0.3
  POSITIVE_OVERLAP: 0.8
  POSITIVE_RATIO: 0.25
  DEFAULT_BOX_NUM: 300
  SOLVER: Adam
  LEARNING_RATE: 0.001
  STEPSIZE: 50000